// <auto-generated />
using Agencia_viagens.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Agencia_viagens.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Agencia_viagens.Models.Passagem", b =>
                {
                    b.Property<int>("id_passsagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_passsagem"), 1L, 1);

                    b.Property<string>("data_de_ida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("data_de_volta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horario_da_ida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("horario_da_volta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_passsagem");

                    b.ToTable("Passagem");
                });

            modelBuilder.Entity("Agencia_viagens.Models.Reserva", b =>
                {
                    b.Property<int>("id_reserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_reserva"), 1L, 1);

                    b.Property<string>("data_de_ida")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("data_de_volta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("origem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("preco")
                        .HasColumnType("float");

                    b.HasKey("id_reserva");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Agencia_viagens.Models.Usuarios", b =>
                {
                    b.Property<int>("id_cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id_cliente"), 1L, 1);

                    b.Property<string>("cep")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("datacadastro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e_mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nomecompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("senha")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_cliente");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
